anguage: general
sudo: required
services:
  - docker

jobs:
  include:
    - stage: build docker image
      if: branch = master AND type = push
      before_script:
      - ./.travis/setup-git.bash
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
      - ./update-image.sh stack-build
      after_script:
      - git push origin master
