image: matsubara0507/stack-build
output: .
base:
  repo: ubuntu
  tag: "18.04"
template:
  before_env: Dockerfile.1.template
  after_env: Dockerfile.2.template
env:
  stack_version:
    github:
      repo: commercialhaskell/stack
      hook: release
      strip_prefix: v
tags:
- type: value
  keys:
  - latest
  always: true
- type: refer
  ref: https://www.stackage.org/download/snapshots.json
  keys:
  - nightly
  - lts
  - lts-14
  - lts-13
