image: matsubara0507/stack-build
output: .
base:
  repo: ubuntu
  tag: "18.04"
template:
  before_env: Dockerfile.1.template
  after_env: Dockerfile.2.template
env:
  LANG:
    value: C.UTF-8
  LC_ALL:
    value: C.UTF-8
  stack_version:
    github:
      repo: commercialhaskell/stack
      hook: release
      strip_prefix: v
tags:
- type: value
  keys:
  - latest
  - "18.04"
  always: true
