RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    g++ \
    git \
    gnupg \
    libc6-dev \
    libffi-dev \
    libgmp-dev \
    make \
    netbase \
    xz-utils \
    zlib1g-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
